name: Analyze Logs in PR

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - develop

jobs:
  analyze-logs:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    
    steps:
      - name: Wait for Ollama to start
        run: sleep 10  # Ajuste si nécessaire

      - name: Run Ollama Query
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
            REPO: ${{ github.repository }}
            GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        run: node queryOllama.js
        